name: Model Training and Evaluation

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Number of epochs'
        required: true
        default: '10'
      learning_rate:
        description: 'Learning rate'
        required: true
        default: '0.001'
      kaggle_key:
        description: 'Kaggle API key'
        required: true
        default: ''

jobs:
  checkout-and-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mask kaggle_key
        run: |
          echo "::add-mask::${{ github.event.inputs.kaggle_key }}"

      - name: Install Kaggle CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install kaggle

      - name: Set up Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ github.event.inputs.kaggle_key }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download dataset from Kaggle
        run: |
          kaggle datasets download -d gulczas/spotify-dataset
          unzip spotify-dataset.zip -d data
